import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

const aktiv = localFont({
  src: [
    {
      path: "./fonts/aktiv-grotesk/AktivGrotesk-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/aktiv-grotesk/AktivGrotesk-XBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/aktiv-grotesk/AktivGrotesk-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/aktiv-grotesk/AktivGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/aktiv-grotesk/AktivGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-aktiv",
});

const basis = localFont({
  src: [
    {
      path: "./fonts/basis/BasisGrotesqueArabicPro-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/basis/BasisGrotesqueArabicPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/basis/BasisGrotesqueArabicPro-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/basis/BasisGrotesqueArabicPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-basis",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "The Covenant Nation Sangotedo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${basis.variable} ${aktiv.variable} ${caveat.variable} antialiased`}
    >
      <body className="min-h-screen overflow-x-hidden m-0 p-0 flex flex-col bg-white text-black">
        <Navbar />
        <main className="flex-grow-[1]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
